version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: chuu
      MONGO_INITDB_ROOT_PASSWORD: chuu
    networks:
      - chuu-network
    volumes:
      - mongo-data:/data/db

  pinned-backend:
    build: .
    image: jieuniaeyo/chuu-backend:latest
    container_name: chuu-backend
    env_file:
      - .env
    depends_on:
      - mongo
    ports:
      - '443:443'
    networks:
      - chuu-network
    environment:
      - MONGODB_URI=mongodb://chuu:chuu@mongo:27017/chuu?authSource=admin
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  mongo-data:
